services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.32.5
    environment:
      BASEROW_PUBLIC_URL: 'https://gizmo-vanquish-swinging.ngrok-free.dev'
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
